import { McpLibraryItem } from "./mcp"

export const mcpLibraryItems: McpLibraryItem[] = [
	{
		mcpId: "mx-api-index",
		name: "MultiversX - Index API",
		description: "Provides all the tools for interacting with the network API (100+ tools).",
		logoUrl: "https://cdn-icons-png.flaticon.com/512/7778/7778966.png",
		githubUrl: "https://github.com/unievo/mx-mcp/blob/main/servers/mx-api/README-index.md",
		npmPackage: "@unievo/mcp-mx-api-index",
		category: "Index",
		tags: ["MultiversX", "API"],
		author: "Unievo",
		codiconIcon: "server",
		requiresApiKey: false,
		isRecommended: true,
		createdAt: new Date("2025-04-18").toISOString(),
		updatedAt: new Date("2025-04-18").toISOString(),
		llmsInstallationContent:
			"Use any additional installation content here and pay attention at any environment variables required https://raw.githubusercontent.com/unievo/mx-mcp/main/servers/mx-api/README-index.md",
	},
	{
		mcpId: "mx-api-essentials",
		name: "MultiversX - Essentials API",
		description:
			"Provides a selection of essential tools for interacting with the network API (Accounts, Collections, Tokens and Transactions).",
		logoUrl: "https://cdn-icons-png.flaticon.com/512/7778/7778964.png",
		githubUrl: "https://github.com/unievo/mx-mcp/blob/main/servers/mx-api/README-essentials.md",
		npmPackage: "@unievo/mcp-mx-api-essentials",
		category: "Essentials",
		tags: ["MultiversX", "API"],
		author: "Unievo",
		codiconIcon: "server",
		requiresApiKey: false,
		isRecommended: true,
		createdAt: new Date("2025-04-18").toISOString(),
		updatedAt: new Date("2025-04-18").toISOString(),
		llmsInstallationContent:
			"Use any additional installation content here and pay attention at any environment variables required https://raw.githubusercontent.com/unievo/mx-mcp/main/servers/mx-api/README-essentials.md",
	},
	{
		mcpId: "mx-api-network",
		name: "MultiversX - Network API",
		description: "Provides tools for getting information about the Network (Validators, Nodes, Network Configuration).",
		logoUrl: "https://cdn-icons-png.flaticon.com/512/10439/10439399.png",
		githubUrl: "https://github.com/unievo/mx-mcp/blob/main/servers/mx-api/README-network.md",
		npmPackage: "@unievo/mcp-mx-api-network",
		category: "Network",
		tags: ["MultiversX", "API"],
		author: "Unievo",
		codiconIcon: "server",
		requiresApiKey: false,
		isRecommended: true,
		createdAt: new Date("2025-04-18").toISOString(),
		updatedAt: new Date("2025-04-18").toISOString(),
		llmsInstallationContent:
			"Use any additional installation content here and pay attention at any environment variables required https://raw.githubusercontent.com/unievo/mx-mcp/main/servers/mx-api/README-network.md",
	},
	{
		mcpId: "mx-api-accounts",
		name: "MultiversX - Accounts API",
		description: "Provides tools for getting information about the Accounts (Blockchain Addresses).",
		logoUrl: "https://cdn-icons-png.flaticon.com/512/18842/18842058.png",
		githubUrl: "https://github.com/unievo/mx-mcp/blob/main/servers/mx-api/README-accounts.md",
		npmPackage: "@unievo/mcp-mx-api-accounts",
		category: "Accounts",
		tags: ["MultiversX", "API"],
		author: "Unievo",
		codiconIcon: "server",
		requiresApiKey: false,
		isRecommended: true,
		createdAt: new Date("2025-04-18").toISOString(),
		updatedAt: new Date("2025-04-18").toISOString(),
		llmsInstallationContent:
			"Use any additional installation content here and pay attention at any environment variables required https://raw.githubusercontent.com/unievo/mx-mcp/main/servers/mx-api/README-accounts.md",
	},
	{
		mcpId: "mx-api-collections",
		name: "MultiversX - Collections API",
		description:
			"Provides tools for getting information about the Collections (Non-Fungible / Semi-Fungible Collections and Tokens).",
		logoUrl: "https://cdn-icons-png.flaticon.com/512/2659/2659360.png",
		githubUrl: "https://github.com/unievo/mx-mcp/blob/main/servers/mx-api/README-collections.md",
		npmPackage: "@unievo/mcp-mx-api-collections",
		category: "Collections",
		tags: ["MultiversX", "API"],
		author: "Unievo",
		codiconIcon: "server",
		requiresApiKey: false,
		isRecommended: true,
		createdAt: new Date("2025-04-18").toISOString(),
		updatedAt: new Date("2025-04-18").toISOString(),
		llmsInstallationContent:
			"Use any additional installation content here and pay attention at any environment variables required https://raw.githubusercontent.com/unievo/mx-mcp/main/servers/mx-api/README-collections.md",
	},
	{
		mcpId: "mx-api-contracts",
		name: "MultiversX - Contracts API",
		description: "Provides tools for getting information about the Smart Contracts.",
		logoUrl: "https://cdn-icons-png.flaticon.com/512/8790/8790062.png",
		githubUrl: "https://github.com/unievo/mx-mcp/blob/main/servers/mx-api/README-contracts.md",
		npmPackage: "@unievo/mcp-mx-api-contracts",
		category: "Contracts",
		tags: ["MultiversX", "API"],
		author: "Unievo",
		codiconIcon: "server",
		requiresApiKey: false,
		isRecommended: true,
		createdAt: new Date("2025-04-18").toISOString(),
		updatedAt: new Date("2025-04-18").toISOString(),
		llmsInstallationContent:
			"Use any additional installation content here and pay attention at any environment variables required https://raw.githubusercontent.com/unievo/mx-mcp/main/servers/mx-api/README-contracts.md",
	},
	{
		mcpId: "mx-api-roles",
		name: "MultiversX - Roles API",
		description: "Provides tools for getting information about the Account Roles for Collections and Tokens.",
		logoUrl: "https://cdn-icons-png.flaticon.com/512/1865/1865757.png",
		githubUrl: "https://github.com/unievo/mx-mcp/blob/main/servers/mx-api/README-roles.md",
		npmPackage: "@unievo/mcp-mx-api-roles",
		category: "Roles",
		tags: ["MultiversX", "API"],
		author: "Unievo",
		codiconIcon: "server",
		requiresApiKey: false,
		isRecommended: true,
		createdAt: new Date("2025-04-18").toISOString(),
		updatedAt: new Date("2025-04-18").toISOString(),
		llmsInstallationContent:
			"Use any additional installation content here and pay attention at any environment variables required https://raw.githubusercontent.com/unievo/mx-mcp/main/servers/mx-api/README-roles.md",
	},
	{
		mcpId: "mx-api-tokens",
		name: "MultiversX - Tokens API",
		description: "Provides tools for getting information about the Fungible Tokens.",
		logoUrl: "https://cdn-icons-png.flaticon.com/512/5171/5171287.png",
		githubUrl: "https://github.com/unievo/mx-mcp/blob/main/servers/mx-api/README-tokens.md",
		npmPackage: "@unievo/mcp-mx-api-tokens",
		category: "Tokens",
		tags: ["MultiversX", "API"],
		author: "Unievo",
		codiconIcon: "server",
		requiresApiKey: false,
		isRecommended: true,
		createdAt: new Date("2025-04-18").toISOString(),
		updatedAt: new Date("2025-04-18").toISOString(),
		llmsInstallationContent:
			"Use any additional installation content here and pay attention at any environment variables required https://raw.githubusercontent.com/unievo/mx-mcp/main/servers/mx-api/README-tokens.md",
	},
	{
		mcpId: "mx-api-transactions",
		name: "MultiversX - Transactions API",
		description: "Provides tools for getting information about the Transactions.",
		logoUrl: "https://cdn-icons-png.flaticon.com/512/8487/8487150.png",
		githubUrl: "https://github.com/unievo/mx-mcp/blob/main/servers/mx-api/README-transactions.md",
		npmPackage: "@unievo/mcp-mx-api-transactions",
		category: "Transactions",
		tags: ["MultiversX", "API"],
		author: "Unievo",
		codiconIcon: "server",
		requiresApiKey: false,
		isRecommended: true,
		createdAt: new Date("2025-04-18").toISOString(),
		updatedAt: new Date("2025-04-18").toISOString(),
		llmsInstallationContent:
			"Use any additional installation content here and pay attention at any environment variables required https://raw.githubusercontent.com/unievo/mx-mcp/main/servers/mx-api/README-transactions.md",
	},
	{
		mcpId: "mx-mcp",
		name: "MultiversX - Official MCP",
		description:
			"Provides basic functionality like creating PEM wallets, getting the wallet address, getting the balance of the wallet and sending tokens (EGLD, Fungible, SFT, NFT, MetaESDT).",
		logoUrl: "https://tools.multiversx.com/assets-cdn/identities/multiversx/icon.png",
		githubUrl: "https://github.com/multiversx/mx-mcp",
		npmPackage: "@multiversx/mcp",
		category: "MultiversX",
		tags: ["Wallet", "Transactions"],
		author: "MultiversX",
		codiconIcon: "server",
		requiresApiKey: false,
		isRecommended: true,
		createdAt: new Date("2025-04-10").toISOString(),
		updatedAt: new Date("2025-04-10").toISOString(),
		llmsInstallationContent:
			"Use any additional installation content here and pay attention at any environment variables required @https://github.com/multiversx/mx-mcp",
	},
]
